# Generated by Django 3.1.3 on 2020-11-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20201204_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesResultPerMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_month', models.DateField(verbose_name='売上月')),
                ('total_amount', models.PositiveIntegerField(verbose_name='合計売上金額')),
                ('target_amount', models.PositiveIntegerField(verbose_name='目標売上金額')),
            ],
            options={
                'verbose_name': '月別合計売上金額',
                'verbose_name_plural': '月別合計売上金額',
                'db_table': 'sales_result_per_month',
                'managed': False,
            },
        ),
    ]
